apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-example-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
