apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-cluster
  name: letsencrypt-cluster
spec:
  acme:
    email: test@test.com
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-cluster
    server: https://acme-v02.api.letsencrypt.org/directory
