apiVersion: v1
kind: ServiceAccount
metadata:
  name: yourbiz-prod-admin
  namespace: yourbiz-prod
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: yourbiz-prod-admin
  namespace: yourbiz-prod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: yourbiz-prod-admin
  namespace: yourbiz-prod
subjects:
  - kind: ServiceAccount
    name: yourbiz-prod-admin
    namespace: yourbiz-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yourbiz-prod-admin
