{{- if default "" .Values.externalUrl }}
{{- $fullName := include "gitlab-ce.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gitlab-ce.labels" . | nindent 4 }}    
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gitlab-ce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gitlab-ce.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gitlab-ce.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            ## General GitLab Configs
            ##
            - name: GITLAB_OMNIBUS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: gitlab_omnibus_config
            - name: GITLAB_ROOT_PASSWORD
              {{- if default "" .Values.gitlabRootPassword }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: gitlab-root-password
              {{ end }}
            - name: EXTERNAL_URL
              value: {{ default "" .Values.externalUrl | quote }}
            ## DB configuration
            ##
            - name: DB_HOST
              value: {{ template "gitlab-ce.postgresql.fullname" . }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: db-password
            - name: DB_DATABASE
              value: {{ .Values.postgresql.postgresDatabase | quote }}
            ## Redis configuration
            ##
            - name: REDIS_HOST
              value: {{ template "gitlab-ce.redis.fullname" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: redis-password
          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          livenessProbe:
            httpGet:
              path: /-/liveness
              port: {{ .Values.livenessPort }}
            # This pod takes a very long time to start up. Be cautious when
            # lowering this value to avoid Pod death during startup.
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: {{ .Values.readinessPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: gitlab-etc
              mountPath: /etc/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: gitlab-etc
          {{- if .Values.persistence.gitlabEtc.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.gitlabEtc.existingClaim }}
            claimName: {{ .Values.persistence.gitlabEtc.existingClaim }}
            {{- else }}
            claimName: {{ $fullName }}-etc
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: gitlab-data
          {{- if .Values.persistence.gitlabData.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.gitlabData.existingClaim }}
            claimName: {{ .Values.persistence.gitlabData.existingClaim }}
            {{- else }}
            claimName: {{ $fullName }}-data
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
