apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatype-nexus
  namespace: yourbiz-infra
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /opt/disks/vdb/sonatype-nexus-pv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: yourdomain.com/bare-metal-storage-name
              operator: In
              values:
                - yourbiz-slave000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-nexus
  namespace: yourbiz-infra
spec:
  storageClassName: ""
  volumeName: sonatype-nexus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---

