apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  namespace: yourbiz-infra
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /opt/disks/vdb/docker-registry-pv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: yourdomain.com/bare-metal-storage-name
              operator: In
              values:
                - yourbiz-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
  namespace: yourbiz-infra
spec:
  storageClassName: ""
  volumeName: docker-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---

