image:
  repository: registry
  tag: 2.7.1
  pullPolicy: IfNotPresent

securityContext:
  enabled: false

service:
  name: registry
  type: ClusterIP
  # clusterIP:
  port: 5000

ingress:
  enabled: true
  path: /
  # Used to create an Ingress record.
  hosts:
    - registry.yourdomain.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster"
  tls:
    - secretName: docker-registry
      hosts:
        - registry.yourdomain.com

persistence:
  enabled: true
  existingClaim: docker-registry

secrets:
  htpasswd: "yourbiz:$2y$05$LpHzH7fZ7MULIQiSvnunBekjX83SkMCwGQfKKCuKK7n1kpnxTaEZe"
