apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster
spec:
  acme:
    email: yourbiz@yourdomain.com
    privateKeySecretRef:
      name: letsencrypt-cluster
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
