apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4}}
  {{- if .Values.metrics.enabled }}
  annotations:
    {{ toYaml .Values.metrics.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4}}
