apiVersion: v1
kind: Service
metadata:
  name: {{ include "context.fullname" . }}
  labels:
{{ include "context.labels" . | indent 4 }}
spec:
  type: {{ .Values.context.service.type }}
  ports:
    - port: {{ .Values.context.service.externalPort }}
      targetPort: {{ .Values.context.service.externalPort }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "context.fullname" . }}
subsets:
  - addresses:
      # list all external ips for this service
      - ip: {{ .Values.context.service.externalIp }}
    ports:
      - port: {{ .Values.context.service.externalPort }}
        protocol: TCP