{{- $fullName := include "yourbiz-be.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "yourbiz-be.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret  }}
  oss-access-key-id: {{ .Values.oss.accessKeyId }}
  oss-access-key-secret: {{ .Values.oss.accessKeySecret }}
  mail-password: {{ .Values.mail.password }}
  sms-access-key-id: {{ .Values.sms.accessKeyId }}
  sms-access-key-secret: {{ .Values.sms.accessKeySecret }}
  wechat-token: {{ .Values.wechat.token }}
  wechat-app-secret: {{ .Values.wechat.appSecret }}
  ding-talk-access-token: {{ .Values.dingTalk.accessToken }}

  {{- if not .Values.mysql.enabled }}
  mysql-password: {{ .Values.externalMySql.password }}
  {{- end }}
